<?php
$agencyDao = new \Classes\Dao\AgencyDao();
$agency = $agencyDao->getAgency();

?><!DOCTYPE html>
<html >
<head>
	<meta charset="UTF-8">
	<title><?php echo $agency->name; ?> - LOGIN</title>
	<link rel="stylesheet" href="/assets/admin/css/login/style.css">
</head>

<body>
<hgroup>
	<img style="height: 150px" id="logo" src="<?php echo SITE_LOGO ?>" alt="<?php echo $agency->name ?>" />
</hgroup>

<?php echo $this->layout()->content; ?>


<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

<script src="/assets/admin/\scripts/login/index.js"></script>

</body>
</html>
