<form method="post" action="">

	<?php if ($this->message): ?>
		<div class="error-login">
			<?php echo $this->message ?>
		</div>
	<?php endif ?>

	<div class="group">
		<input type="text" name="username"><span class="highlight"></span><span class="bar"></span>
		<label><?php echo $this->translate("Username"); ?></label>
	</div>
	<div class="group">
		<input type="password" name="password"><span class="highlight"></span><span class="bar"></span>
		<label><?php echo $this->translate("Password"); ?></label>
	</div>
	<button type="submit" class="button buttonBlue"><?php echo $this->translate("Login"); ?>
		<div class="ripples buttonRipples"><span class="ripplesCircle"></span></div>
	</button>
</form>