<div class="panel panel-default">
	<div class="panel-heading">Commandes et Réservations </div>
	<div class="panel-body">
		<table style="font-size:12px" class="table table-bordered">
			<thead>
			<tr>
				<th>Ref</th>
				<th>Client</th>
				<th>Email</th>
				<th>Date</th>
				<th></th>

				<th>Prix payé</th>
				<th>Etat commande</th>
				<th>Actions</th>
			</tr>

			</thead>



			<tbody>

			<?php
			foreach($this->commandes as $ligne){

				$client=$this->clients[$ligne->client_id];
				$date=new DateTime($ligne->date);
				$date_arrivee=new DateTime($ligne->date_arrivee);

				?>

				<tr>
					<td>
						<?php echo $this->escape($ligne->id); ?>

					</td>
					<td><a href="/administration/clients/details/id/<?php echo $client->id ?>"><?php echo $this->escape($client->sexe.' '.$client->nom.' '.$client->prenom); ?></a></td>
					<td><?php echo $this->escape($client->email); ?></td>

					<td><?php echo $date->format('d/m/Y H:i'); ?></td>
					<td></td>

					<td><?php echo FNC::MoneyF($ligne->prix_total); ?></td>
					<td>
						<?php echo FNC::getCommandeEtat($ligne); ?>
					</td>
					<td>
						<a href="/administration/commandes/details/id/<?php echo $ligne->id ?>">Afficher détails</a>

					</td>

				</tr>
				<tr>

				</tr>
			<?php } ?>

			</tbody>
		</table>
	</div>
</div>