<div class="row">
    <div class="col-sm-8">
        <div class="section1">
            <h3 class="ttr_fc">Paramètres Site</h3>
            <form name="" method="post" action="">
                <p class="ligne-adm1">
                    <label>Nom Site</label>
                    <input type="text" name="name" id="name" class="text-input medium-input" value="<?php echo $this->config->name ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Url</label>
                    <input type="text" name="url" id="url" class="text-input medium-input" value="<?php echo $this->config->url ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Description</label>
                    <textarea name="description" class="text-input medium-input" id="description" style="height:100px"><?php echo $this->config->description ?></textarea>
                </p>
                <p class="ligne-adm1">
                    <label>Email</label>
                    <input type="text" name="email" id="email" class="text-input medium-input" value="<?php echo $this->config->email ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Email2</label>
                    <input type="text" name="email2" id="email2" class="text-input medium-input" value="<?php echo $this->config->email2 ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Tél</label>
                    <input type="text" name="tel" id="tel" class="text-input medium-input" value="<?php echo $this->config->tel ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Fax</label>
                    <input type="text" name="fax" id="fax" class="text-input medium-input" value="<?php echo $this->config->fax ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Gsm</label>
                    <input type="text" name="gsm" id="gsm" class="text-input medium-input" value="<?php echo $this->config->gsm ?>" >
                </p>
                <p class="ligne-adm1">
                    <label>Adresse</label>
                    <textarea name="adresse" class="text-input medium-input" id="adresse" style="height:120px"><?php echo $this->config->adresse ?></textarea>
                </p>

                <p class="ligne-adm1">
                    <label>Taux de change :</label>
                    <input type="text" name="taux_change" id="taux-change" class="text-input medium-input" value="<?php echo $this->config->taux_change ?>" style="width:120px !important; margin-right:5px" > <strong class="font-weight:bold">MAD  = 1 € </strong>
                </p>

                <p class="ligne-adm1">
                    <label>Code analytics et autres</label>
                    <textarea name="analytics" class="text-input medium-input" id="analytics" style="height:280px"><?php echo $this->config->analytics ?></textarea>
                </p>

                <p class="ligne-adm1">
                    <label>Activer le paiement :</label>
                    <input type="checkbox" value="1" name="has_payment" id="has_payment-form" <?php echo ($this->config->has_payment)?'checked="checked"':'' ?> >
                </p>
                <p class="ligne-adm1">
                    <label>Activer commande sans paiement :</label>
                    <input type="checkbox" value="1" name="can_command" id="can_command-form" <?php echo ($this->config->can_command)?'checked="checked"':'' ?> >
                </p>

                <p class="ligne-adm1">
                    <label>Site en ligne  :</label>
                    <input type="checkbox" value="1" name="online" id="online-form" <?php echo ($this->config->online)?'checked="checked"':'' ?> >
                </p>

                <p class="ligne-adm1">
                    <label>Latitude :</label>
                    <input type="text" name="lat" id="lat-form" class="text-input medium-input" value="<?php echo $this->config->lat ?>" >
                </p>

                <p class="ligne-adm1">
                    <label>Longitude :</label>
                    <input type="text" name="lng" id="lng-form" class="text-input medium-input" value="<?php echo $this->config->lng ?>" >
                </p>

                <input type="submit" name="subeditsettings" value="Modifier" class="button" />

            </form>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="section1">
            <form action="<?php echo $this->url(array('controller'=>'settings','action'=>'index'));?>" method="post" class="form" id="formauth">
                <input type="hidden" name="id" value="<?php echo $this->escape($this->user->id); ?>" id="id" />
                <h3 class="ttr_fc">Accès Administrateur</h3>
                <p>
                    <label for="email">Login Administrateur : <span class="required">*</span></label>
                    <input type="text" name="username" id="username" style="width:200px" value="<?php echo $this->escape(stripslashes($this->user->username)); ?>" class="text-input small-input">

                </p>

                <p>
                    <label for="textfield" >Mot de Passe : * </label>
                    <input type="password" name="password" id="password" value="" style="width:200px" class="text-input small-input">

                </p>

                <p>
                    <label for="password">Confirmer Mot de Passe : *</label>
                    <input type="password" name="confirmPassword" id="confirmPassword" style="width:200px" value="" class="text-input small-input">

                </p>
                <p>
                    <input type="submit" name="Enregistrer" id="Enregistrer" value="Enregistrer" class="button">
                </p>

                <!-- end of box-body -->
            </form>
        </div>
    </div>
</div>