<div class="clear"></div> <!-- End .clear -->
<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Social</h3>
					
					
					<div class="clear"></div>
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
				  <div class="tab-content default-tab" id="tab1">

                            

                                <form action="" method="post" enctype="multipart/form-data">

                                    <fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->

                                      
                                      <p>

                                        <label>Lien facebook</label>

                                          <input class="text-input large-input" type="text" id="facebook" name="facebook" value="<?php echo $this->escape($this->social->facebook); ?>" /> 

                                        </p>
                                   
                                  <p>

                                        <label>Lien twitter</label>

                                          <input class="text-input large-input" type="text" id="twitter" name="twitter" value="<?php echo $this->escape($this->social->twitter); ?>" /> 

                                        </p>

                                    
                                      <p>

                                      <p>

                                        <label>Lien google+</label>

                                          <input class="text-input large-input" type="text" id="google" name="google" value="<?php echo $this->escape($this->social->google); ?>" /> 

                    <input type="hidden" name="visible" value="1" />
                                        </p>

                                        

                                        <label>Lien instagram</label>

                                          <input class="text-input large-input" type="text" id="instagram" name="instagram" value="<?php echo $this->escape($this->social->instagram); ?>" /> 

										<input type="hidden" name="visible" value="1" />
                                        </p>

                                         <p>

                                        <label>Lien youtube</label>

                                          <input class="text-input large-input" type="text" id="youtube" name="youtube" value="<?php echo $this->escape($this->social->youtube); ?>" /> 

                    <input type="hidden" name="visible" value="1" />
                                        </p>


                                         <p>

                                        <label>Lien pintrest</label>

                                          <input class="text-input large-input" type="text" id="pintrest" name="pintrest" value="<?php echo $this->escape($this->social->pintrest); ?>" /> 

                    <input type="hidden" name="visible" value="1" />
                                        </p>

                                         

                                        

                                      <p>

                                        <input class="button" type="submit" name="subform" value="  Modifier  " id="subform"  />

                                        </p>

                                        

                                    </fieldset>

                                    

                                    <div class="clear"></div><!-- End .clear -->

                                    

                                </form>

                               

                                

                            </div>
                   
					
				</div> <!-- End .content-box-content -->
				
			</div> <!-- End .content-box -->